### ISSUE TITLE
Upstream all models to coreboot

### ISSUE THREAD

**Issue by ghost** [system76/coreboot#40]
I was wondering why the lemp9 is current the only device from you which is upstream in the Coreboot Repo

In this Repo and firmware-open Repo

- [x] [addw1](https://review.coreboot.org/c/coreboot/+/48421)
- [x] [addw2](https://review.coreboot.org/c/coreboot/+/48422)
- [ ] [bonw14](https://review.coreboot.org/c/coreboot/+/49173)
- [x] [darp5](https://review.coreboot.org/c/coreboot/+/51870)
- [x] [darp6](https://review.coreboot.org/c/coreboot/+/52063)
- [x] [darp7](https://review.coreboot.org/c/coreboot/+/52349)
- [x] [galp2](https://review.coreboot.org/c/coreboot/+/52219)
- [x] [galp3](https://review.coreboot.org/c/coreboot/+/52218)
- [x] [galp3-b](https://review.coreboot.org/c/coreboot/+/52217)
- [x] [galp3-c](https://review.coreboot.org/c/coreboot/+/51832)
- [x] [galp4](https://review.coreboot.org/c/coreboot/+/52034)
- [x] [galp5](https://review.coreboot.org/c/coreboot/+/52350)
- [x] [gaze14](https://review.coreboot.org/c/coreboot/+/52295)
- [x] [gaze15](https://review.coreboot.org/c/coreboot/+/47822)
- [ ] [gaze16](https://review.coreboot.org/c/coreboot/+/56956)
- [x] [lemp9](https://review.coreboot.org/c/coreboot/+/38463)
- [x] [lemp10](https://review.coreboot.org/c/coreboot/+/52294)
- [x] [oryp5](https://review.coreboot.org/c/coreboot/+/47892)
- [x] [oryp6](https://review.coreboot.org/c/coreboot/+/47768)
- [x] [oryp7](https://review.coreboot.org/c/coreboot/+/52296)
- [ ] [oryp8](https://review.coreboot.org/c/coreboot/+/57652)

Why the are all not upstream in Coreboot? I think it's good that you develop Coreboot for these models, but I don't think it's good that they don't go upstream into Coreboot.

You (and other OEMs) are use Barebones from Clevo.

**Comment by jackpot51** [comment]
We try, but there are drivers to upstream and some are still unapproved

**Comment by c0d3z3r0** [comment]
@jackpot51 what drivers are you referring to?

**Comment by c0d3z3r0** [comment]
- https://review.coreboot.org/c/coreboot/+/43614 - you have a TODO
- https://review.coreboot.org/c/coreboot/+/46300 - system76 failed to adapt the commit message and did not respond
- https://review.coreboot.org/c/coreboot/+/43615 - no response from system76 since July; TODO on your side: make driver generic
- https://review.coreboot.org/c/coreboot/+/43616 - rework after review needed; no response from system76 since August
- https://review.coreboot.org/c/coreboot/+/35802 - rework after review needed; no reponse from system76

So, you see, it's not our fault but yours ;)

**Comment by LeCaNo2012** [comment]
@jackpot51 Please leave the Issue open until the most models are upstream
@c0d3z3r0 In my opinion, this does not shed any good light on System76

**Comment by jackpot51** [comment]
Since it is one of our goals to upstream every supported model, I will reopen this issue.

Our priority is to develop open source, production quality firmware for our products. We do this regardless of upstream constraints. We sometimes work around missing features or bugs in upstream in ways that are not acceptable for upstream patches, such as https://review.coreboot.org/c/coreboot/+/43615. Preparing such patches for upstream is time consuming, and does not change the end user experience. This means that while there are outstanding issues or new models to develop, preparing such patches for upstream is not our highest priority.

So please understand that while our goal is to move all of the changes upstream that are required to build production quality firmware for our products, this goal is one that is often sidelined by the need to have the production quality firmware in the first place. We perform all pre-release product development absolutely in the open under either the license of the project or GPLv3, even though this is not necessary for compliance until products begin to ship to end users. For us to continue to do this, it is required that we are able to stage changes in our own fork of the project which we use to produce the first versions of production firmware. This model worked well with the lemp9, which was the first system upstreamed. 

The upstreaming process of the next two products, the oryp6 and bonw14, has been stalled due to issues with the NVIDIA Optimus and I2C smart amp patches mentioned above. We do not have a good method to make the NVIDIA Optimus patch generic at this time, but are hoping that the PCIe RTD3 patches recently submitted for use on TGL-U products will serve as a good base for this functionality. When we have solutions to upstream review comments, these solutions will be uploaded as new patches.

**Comment by crawfxrd** [comment]
All non-TGL boards now have an upstream MR. Most are WIP as I do not have the model with me to test on.

**Comment by crawfxrd** [comment]
Models have been rebased and TGL-U models have been added.

**Comment by crawfxrd** [comment]
Good enough. Most will be in the upcoming 4.15 release.

bonw14 is questionable due to it only having NVIDIA graphics, and being a PITA to flash is something goes wrong.
gaze16 and oryp8 may still have more changes.
